config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :user_meetups
  resources :meetups
  resources :campaigns
  resources :users
  get "/login", to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_meetups
  has_many :meetups, through: :user_meetups, dependent: :destroy
  has_many :characters

  #not really on board?
  has_many :campaigns, through: :characters
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_name, presence: true
  validates :email_address, presence: true, if: :has_at_and_period?
  validates :user_name, uniqueness: { case_sensitive: false }

  validates :email_address, uniqueness: { case_sensitive: false }
  validate :has_at_and_period?

  def has_at_and_period?
    unless self.email_address.include?("@") && self.email_address.include?(".")
      errors.add(:email_address, "This is not a valid email address.")
    end
  end

  # def get_all_meetups
  #   self.meetups
  # end

  def full_name
    self.first_name + " " + self.last_name
  end

  #should use start_date = Time.now when creating a new user profile
  def format_start_date
    if self.start_date
      formatted_date = self.start_date.to_date
      year = formatted_date.cwyear
      day = formatted_date.day
      month = month_conversion
      "#{month} #{day}, #{year}"
    end
  end

# Helper method
  def month_conversion
    month_number = self.start_date.to_date.month
    if month_number == 1
      "January"
    elsif month_number == 2
      "February"
    elsif month_number == 3
      "March"
    elsif month_number == 4
      "April"
    elsif month_number == 5
      "May"
    elsif month_number == 6
      "June"
    elsif month_number == 7
      "July"
    elsif month_number == 8
      "August"
    elsif month_number == 9
      "September"
    elsif month_number == 10
      "October"
    elsif month_number == 11
      "November"
    elsif month_number == 12
      "December"
    end
  end

  #method to get list of characters
  def get_list_of_characters
    # character_list = []
    # Character.all.each do |character|
    #   character.campaign.meetups.each do |meetup|
    #     meetup.users.each do |user|
    #       if user.id == self.id
    #         byebug
    #         character_list << character.char_name
    #       else
    #         puts "I'm here"
    #       end
    #     end
    #   end
    # end
    # character_list.uniq
    self.characters.map do |character|
      character.char_name
    end
  end

  # #method to get list of campaigns_ids
  # def get_list_of_campaign_ids
  #   self.get_all_meetups.map do |meetup|
  #       meetup.campaign_id
  #   end
  # end
  #
  # #methd to get list of campaigns
  # def get_list_of_campaigns
  #   get_list_of_campaign_ids.map do |id|
  #     Campaign.find(id)
  #   end
  # end
  #
  # def get_list_of_campaign_titles
  #   get_list_of_campaigns.map do |campaign|
  #     campaign.title
  #   end
  # end

  def get_list_of_campaign_titles
    # campaign_titles = []
    # Campaign.all.each do |campaign|
    #   campaign.meetups.each do |meetup|
    #     meetup.users.each do |user|
    #       if user.id == self.id
    #         campaign_titles << campaign.title
    #       end
    #     end
    #   end
    # end
    # campaign_titles.uniq
    self.campaigns.map do |campaign|
      campaign.title
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  def show

  end

  def new
    @user = User.new
  end

  def create
    # @user = User.new(user_params(:first_name, :last_name, :username, :email_address, :start_date))
    @user = User.new(user_params(:first_name, :last_name, :email_address, :user_name, :password))
    @user.start_date = Time.now
    if @user.save
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit

  end

  def update
    if @user.update(user_params(:first_name, :last_name, :email_address))
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user.destroy
    redirect_to home_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params(*args)
    params.require(:user).permit(*args)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<h3 class="heading-3" style="color: rgba(104,22,18,1);">Personal Info</h3>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %> &nbsp
  <% end %>
<% end %>

<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :email_address %>
  <%= f.submit "Save" %>
<% end %>

app/views/users/new.erb
<div class="login-img">
  <div class="img-screen">
    <div class="row">
      <div class="col">

        <h1 class="sign-up-heading">Sign Up</h1>
        <h4 class="notice"><%= flash[:notice] %></h4>

        <% if flash[:errors] %>
        <div class="alert alert-danger">
          <% flash[:errors].each do |error| %>
            <%= error %> &nbsp
          <% end %>
          </div>
        <% end %>

          <%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>

            <%= f.text_field :user_name %>


            <%= f.password_field :password %>

            <%= f.text_field :first_name %>

            <%= f.text_field :last_name %>

            <%= f.text_field :email_address %>

            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/users/show.erb
<div class="container">
  <div class="row">
    <div class="col-md-6" id="user-img-col">
      <div class="img-box">
        <img src="<%=asset_path('dragon.jpg')%>" alt="dragon" />
      </div>
    </div>
  <!-- </div>
  <div class="row"> -->
    <div class="col-md-6  user-info">
      <h3 class="heading-3"><%= @user.full_name %> </h3>
      <ul>
        <li>Email: <%= @user.email_address %></li>
        <li>Start Date: <%= @user.format_start_date %></li>
      </ul>
      <%= link_to "Edit Info", edit_user_path(@user), class: "btn" %>
    </div>
  </div>
  <br />

  <div class="row">
    <div class="col-md-6 user-info-2">
      <h4 class="heading-4">Characters</h4>
    </div>
    <div class="col-md-6 user-info-2">
      <h4 class="heading-4">Campaigns</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 user-info-2">
      <ul>
        <% @user.characters.each do |character| %>
        <li><%= link_to character.char_name, character_path(Character.find(character.id)) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-6 user-info-2">
      <ul>
        <% @user.get_list_of_campaign_titles.each do |title| %>
        <li><%= title %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 user-info-2">
      <h4 class="heading-4">Meetups</h4>
      <ul>
        <% @user.meetups.each do |mu| %>
        <li><%= link_to mu.format_meet_time, meetup_path(mu) %> - <%= mu.campaign.title %></li>
        <% end %>
      </ul>
    </div>
</div>