config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :user_meetups
  resources :meetups
  resources :campaigns
  resources :users
  get "/login", to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :campaign

  belongs_to :user

  validates :campaign_id, numericality: {greater_than_or_equal_to: 1}
  validates :user_id, uniqueness:{ scope: :campaign_id, message: "only one character per campaign" } # <-- ADDED FOR BLOG
  validates :alignment, presence: true, unless: :dungeon_master?
  validates :char_name, presence: true
  validates :race, presence: true, unless: :dungeon_master?
  validates :klass, presence: true, unless: :dungeon_master?
  validates :user_id, numericality: {greater_than_or_equal_to: 1}, unless: :dungeon_master?
  validates :level, numericality: {greater_than_or_equal_to: 1}, unless: :dungeon_master?

  def dungeon_master?
    char_name == "Dungeon Master"
  end

  def self.alignment_list
    ["Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "Neutral Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil"]
  end

  def self.race_list
    ["Gnome", "Halfling", "Dwarf", "Elf", "Half-Elf", "Teifling", "Human", "Dragonborn", "Half-Orc"]
  end

  def self.klass_list
    ["Bard", "Barbarian", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rouge", "Sorcerer", "Warlock", "Wizard"]
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :find_character, only: [:show, :edit, :update]
  def index
    @characters = Character.all
  end

  def show

  end

  def new
    @character = Character.new
    @campaign = UserMeetup.last.meetup.campaign.id
    # byebug
    @alignments = Character.alignment_list
    @races = Character.race_list
    @klasses = Character.klass_list
    # flash[:meetuptransfer2] = flash[:meetuptransfer]
  end

  def create
    flash[:meetup2] = flash[:meetup]
    @character = Character.new(character_params(:campaign_id, :alignment, :char_name, :race, :weapon, :level, :klass, :user_id))
    @character.save
    if @character.valid?
      redirect_to character_path(@character)
    else
      flash[:errors] = @character.errors.full_messages
      redirect_to meetups_path
    end
  end

  def edit

  end

  def update
    @character.update(character_params(:weapon, :level))
    redirect_to character_path(@character)
  end

  private

  def find_character
    @character = Character.find(params[:id])
  end

  def character_params(*args)
    params.require(:character).permit(*args)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/edit.erb
<h3 class="show-char-name">Edit <%= @character.char_name %></h3>

<%= bootstrap_form_for(@character) do |f| %>
  <%= f.text_field :weapon %>
  <%= f.number_field :level %>
  <%= f.submit %>
<% end %>

app/views/characters/new.erb
<h3 class="show-char-name">Create a Character</h3>
<%= bootstrap_form_for(@character, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
<%= f.hidden_field :campaign_id, :value => @campaign %>
<%= f.text_field :char_name, label: "Character Name" %>
<%= f.select :alignment, @alignments %>
<%= f.select :race, @races %>
<%= f.text_field :weapon %>
<%= f.number_field :level%>
<%= f.select :klass, @klasses, label: "Class" %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.submit %>
<% end %>

app/views/characters/show.erb
<h3 class="show-char-name"><%= @character.char_name %></h3>

<ul>
  <li>Current campaign: <%= @character.campaign.title %></li>
  <li>Alignment: <%= @character.alignment %></li>
  <li>Race: <%= @character.race %></li>
  <li>Weapon: <%= @character.weapon %></li>
  <li>Level: <%= @character.level %></li>
  <li>Class: <%= @character.klass %></li>
</ul>

<button type="button" class="btn"><%= link_to "Edit", edit_character_path(@character), class: "edit-char-btn" %></button>