config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :user_meetups
  resources :meetups
  resources :campaigns
  resources :users
  get "/login", to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :meetups
  has_many :characters


  # validates :completed, presence: true
  validates :title, presence: true
  validates :expect_number_of_meetups, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :difficulty, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :max_number_of_characters, numericality: true
  validates :max_number_of_characters, numericality: { only_integer: true }

  # validate :campaign_character_count
  # validate :has_at_least_one_DM
  # validate :has_at_least_one_character

  # def campaign_character_count
  #   if self.max_number_of_characters
  #     if self.characters.length < 1
  #       errors.add(:max_number_of_characters, "You need at least one Dungeon Master and one character!")
  #     elsif self.characters.length > self.max_number_of_characters
  #       errors.add(:max_number_of_characters, "Sorry, this campaign is full. Please choose another campaign.")
  #     end
  #   end
  # end

  def list_of_character_names
    if self.max_number_of_characters
      self.characters.map do |character|
        character.char_name
      end
    end
  end

  # def has_at_least_one_DM
  #   if self.max_number_of_characters
  #     if !list_of_character_names.include?("Dungeon Master")
  #       errors.add(:max_number_of_characters, "You need at least one Dungeon Master!")
  #     end
  #   end
  # end

  # def has_at_least_one_character
  #   if self.max_number_of_characters
  #     one_char = list_of_character_names.any? do |character_name|
  #       character_name != "Dungeon Master"
  #     end
  #     if !one_char
  #       errors.add(:max_number_of_characters, "You need at least one character!")
  #     end
  #   end
  # end

  def completion_meesage
    if self.completed
      "This campaign has either been completed or discontinued. Please choose another campaign."
    else
      "This campaign is currently in progress."
    end
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :find_campaign, only: [:show, :edit, :update]
  def index
    @campaigns = Campaign.all
  end

  def show

  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params(:title, :expect_number_of_meetups, :difficulty, :max_number_of_characters))
    @campaign.save
    if @campaign.valid?
      Character.create(campaign_id: @campaign.id, user_id: current_user.id, char_name: "Dungeon Master")
      flash[:campaign] = @campaign.id
      flash[:campaign_title] = @campaign.title
      redirect_to new_meetup_path
    else
      flash[:errors] = @campaign.errors.full_messages
      redirect_to new_campaign_path
    end
  end

  def edit
    @complete_array = [true, false]
  end

  def update
    @campaign.update(campaign_params(:completed))
    redirect_to campaign_path(@campaign)
  end

  private

  def find_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params(*args)
    params.require(:campaign).permit(*args)
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/edit.erb
<h1 class="heading-1">Campaign Status</h1>

<%= bootstrap_form_for(@campaign) do |f| %>
  <%= f.select :completed, @complete_array, label: "Completed?" %><br><br>

  <%= f.submit "Save" %>
<% end %>

app/views/campaigns/index.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="heading-1">Campaigns</h1>

      <%= button_to "Create New", new_campaign_path, method: "get", class: "my-btn btn-secondary"%>
      <hr>
      </div>
  </div>
    <div class="row">
        <% @campaigns.each do |campaign| %>
        <div class="col-md-4">
          <div class="campaign-card">
            <p class="heading-p"><%= link_to campaign.title, campaign_path(campaign) %></p>
            <ul>
              <li><%= campaign.title %></li>
              <li><%= campaign.expect_number_of_meetups %> Meetups</li>
              <li>Difficulty: <%= campaign.difficulty %></li>
              <li>Max Number of Characters: <%= campaign.max_number_of_characters %></li>
            </ul>
          </div>
        </div>
        <% end %>
    </div>
</div>

app/views/campaigns/new.erb
<h1 class="heading-1">Start A New Campaign</h1>
<p>Note: Since you are starting a new compaign, you shall be Dungeon Master by default.</p>
<% if flash[:errors] %>
<div class="alert alert-danger">
  <% flash[:errors].each do |error| %>
  <%= error %> &nbsp
  <% end %>
</div>
<% end %>
<%= bootstrap_form_for(@campaign, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.hidden_field :completed, value: false %>


  <%= f.text_field :title%>


  <%= f.number_field :expect_number_of_meetups, label: "Number of Meetups" %>


  <%= f.number_field :max_number_of_characters, label: "Character Limit"%>


  <%= f.number_field :difficulty%>

  <%= f.submit%>
<% end %>

app/views/campaigns/show.erb
<h3 class="heading-1"><%= @campaign.title %></h3>
<p><b>Status: </b><%= @campaign.completion_meesage %></p>

<ul>
  <li>Expected No. of Meetups <%= @campaign.expect_number_of_meetups %></li>
  <li>Difficulty: <%= @campaign.difficulty %></li>
  <li>Max No. of Characters <%= @campaign.max_number_of_characters %></li>
</ul>

<%= link_to "Edit", edit_campaign_path(@campaign) %>